// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'edit': string;
  'edit__back': string;
}
export const cssExports: CssExports;
export default cssExports;
